version: '3.0' # specify docker-compose version

# Define the services/ containers to be run
services:
  ngx-admin-prod:  # name of the first service
    container_name: ngx-admin-prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod  # specify the directory of the Dockerfile
    environment:
      NODE_ENV: production
      ___PUBLIC_DSN___:
    ports:
      - "80:80" # specify port mapping
